apiVersion: v1
kind: ServiceAccount
metadata:
  name: knutr-core
  namespace: knutr
  labels:
    app.kubernetes.io/name: knutr-core
    app.kubernetes.io/component: core
    app.kubernetes.io/part-of: knutr
