apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knutr

resources:
  - namespace.yaml
  - core-serviceaccount.yaml
  - core-configmap.yaml
  - core-secret.yaml
  - core-deployment.yaml
  - core-service.yaml
  - ollama-pvc.yaml
  - ollama.yaml
  - plugin-joke.yaml
  - plugin-pingpong.yaml
  - plugin-jargonbuster.yaml
  - plugin-sentinel.yaml
  - exporter-secret.yaml
  - exporter-postgres.yaml
  - plugin-exporter.yaml
  - plugin-summariser.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
